spring:
  application:
    name: XRail
  config:
    import: optional:file:.env[.properties]

  # [1] Database Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:XRail_db}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:XRail_user}
    password: ${MYSQL_PASSWORD:userpassowrd}

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  # [2] JPA & Hibernate
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    sho_sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # [3] Flyway (DB Migration)
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0

  # [4] Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  # [5] Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: XRail-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # [6] Security (OAuth2 - Dummy)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:e384cfe857c0784873f5bef75fd30b6a}
            client-secret: ${KAKAO_CLIENT_SECRET:5Fy7QpX5mUeaxNIoLfp3A3P77jMJPdzH}
            redirect-uri: "http://localhost:${SERVER_PORT:8088}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, account_email
          naver:
            client-id: ${NAVER_CLIENT_ID:p7OFKBP_fHG_VLqmu8UB}
            client-secret: ${NAVER_CLIENT_SECRET:sYBdED_G_2}
            redirect-uri: "http://localhost:${SERVER_PORT:8088}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# [Server Configuration]
server:
  port: ${SERVER_PORT:8088}
  shutdown: graceful

# [Actuator]
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

# [Custom Configuration] JWT
jwt:
  secret: ${JWT_SECRET:XRAIL_V1_SECRET_KEY_FOR_MOM_TREATMENT_DO_NOT_SHARE_2025}
  expiration: ${JWT_EXPIRATION_MS:1800000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:1209600000}

logging:
  level:
    root: INFO
    com.dev.XRail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: INFO # Attack Test : INFO OR WARN